### ISSUE TITLE
Issue while horizontal scaling

### ISSUE THREAD

**Issue by kitokirisaki** [nameserver-systems/pdns-distribute#180]
When adding a new secondary server without zones, the pdns-health-checker on the master receives the error "got unexpected zone count". This is because the secondary server does not have any zones. A zone.modified is then triggered, but fails with the following errors:
- "invalid pdns answer with http status404 with message: Not Found"
- "couldn't get valid answer from powerdns api"

Version: v0.0.308

**Comment by linxside** [comment]
The fix was released with #182 :tada:
